# Generated by Django 5.0.2 on 2024-02-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkateParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shape_size", models.FloatField()),
                ("truck_size", models.FloatField()),
                ("wheels_size", models.IntegerField()),
                ("bearing_brand", models.CharField(max_length=100)),
            ],
        ),
    ]
