# Generated by Django 5.0.2 on 2024-02-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls_skate_parts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skateparts",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="skateparts",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="skateparts",
            name="truck_size",
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name="skateparts",
            table="skate_parts",
        ),
    ]
