# Generated by Django 5.0.2 on 2024-02-21 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls_skate_parts", "0003_alter_skateparts_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="skateparts",
            table="skate_parts",
        ),
    ]
