# Generated by Django 5.0.2 on 2024-02-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls_skate_parts", "0004_alter_skateparts_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skateparts",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
