# Generated by Django 5.0.2 on 2024-02-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls_skate_parts", "0005_alter_skateparts_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shape",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("shape_size", models.FloatField()),
                ("shape_brand", models.CharField(max_length=50)),
                ("maple_or_marfin", models.CharField(max_length=6)),
            ],
            options={
                "db_table": "shape",
                "ordering": ["id"],
            },
        ),
        migrations.DeleteModel(
            name="SkateParts",
        ),
    ]
