# Generated by Django 5.0.2 on 2024-02-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls_skate_parts", "0006_shape_delete_skateparts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shape",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
