# Generated by Django 5.0.2 on 2024-02-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls_skate_parts", "0007_alter_shape_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bearing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bearing_brand", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "bearing",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("truck_size", models.IntegerField()),
                ("truck_brand", models.CharField(max_length=50)),
                ("truck_color", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "truck",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Wheels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wheels_size", models.IntegerField()),
                ("wheels_brand", models.CharField(max_length=50)),
                ("wheels_color", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "wheels",
                "ordering": ["id"],
            },
        ),
    ]
