# Generated by Django 5.0.2 on 2024-02-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("user_age", models.IntegerField()),
            ],
            options={
                "db_table": "user",
                "ordering": ["id"],
            },
        ),
    ]
